service: octopussns-aws

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - "**/**"
  #include:
  #  - "src/model/*.py"
  

provider:
  name: aws
  runtime: python3.8
  region: ${opt:region, 'us-east-2'}
  profile: ${opt:profile, 'rodjul_d00009'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sqs:*"
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - "logs:*"
      Resource: 
        Fn::GetAtt: [ SQSCreateAccount, Arn ] 
  apiKeys:
    - security_dev #https://lorenstewart.me/2017/10/24/serverless-framework-securing-aws-lambda-endpoints/
  stackTags:
    product: "octopus"    

plugins:
  - serverless-plugin-log-retention
  # - serverless-plugin-split-stacks

custom:
  awsconfig: ${file(../../awsconfig.yml):${self:provider.stage}}
  logRetentionInDays: ${self:custom.awsconfig.log_retention_in_days}
  # splitStacks:
  #   perFunction: true
  #   perType: false
  #   perGroupFunction: false
  sns_send_email: OctopusEmailNotify${self:provider.stage}

  

functions:
  SendEmailNotification:
    handler: sns/send_email.lambda_handler
    environment:
      ARN_SNS_EMAIL: !Ref SNSSendEmail
      # PAYER_ID: ${self:custom.awsconfig.aws_account_payer_id}
    runtime: python3.8
    memorySize: 256
    timeout: 300 # 300 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-send_email-${self:provider.stage}
    package:
      include:
        - sns/send_email.py
        # - ../../model/*.py
    # layers:
    #   - "arn:aws:lambda:us-east-2:${self:custom.awsconfig.aws_account_id}:layer:model_octopus:${self:custom.awsconfig.layer_model_octopus_version}"
    events:
      - sns: arn:aws:sns:${self:provider.region}:${self:custom.awsconfig.aws_account_id}:${self:custom.sns_send_email}



resources:
  Resources:
    SNSSendEmail:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.sns_send_email}
        DisplayName: "octopus-seginfo-notification"
        # DisplayName: "Envia email notificando o status do processo"
        Subscription:
          - Endpoint: "rodrigo.juliano@totvs.com.br"
            Protocol: "email"             