dev:
  log_retention_in_days: 1
  aws_account_id: 826839167791
  aws_account_payer_id: 210272193452
  aws_role_lambda: octopus_lambda
prod:
  log_retention_in_days: 7
  aws_account_id: 826839167791
  aws_account_payer_id: 210272193452
  aws_role_lambda: octopus_lambda
