service: octopus

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - "**/**"
  #include:
  #  - "src/model/*.py"
  

provider:
  name: aws
  runtime: python3.6
  region: ${opt:region, 'us-east-2'}
  profile: ${opt:profile, 'rodjul_d00009'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "sqs:*"
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - "logs:*"
      Resource: 
        Fn::GetAtt: [ SQSCreateAccount, Arn ] 
  apiKeys:
    - security_dev #https://lorenstewart.me/2017/10/24/serverless-framework-securing-aws-lambda-endpoints/

plugins:
  - serverless-plugin-log-retention
  - serverless-s3-sync
  # - serverless-plugin-split-stacks

custom:
  awsconfig: ${file(awsconfig.yml):${self:provider.stage}}
  # splitStacks:
  #   perFunction: true
  #   perType: false
  #   perGroupFunction: false
  sqs_name: "CreateAccount"
  sqs_compliance_new_check: "ComplianceNewCheck"
  sqs_compliance_cis_new_check: "ComplianceCISNewCheck"
  s3Sync:
    - bucketName: "octopus-site"
      localDir: public/build/


functions:
  create_account:
    handler: src/lambda_create_account.lambda_handler
    environment:
      URL_SQS: "https://sqs.${self:provider.region}.amazonaws.com/${self:custom.awsconfig.aws_account_id}/${self:custom.sqs_name}"
      PAYER_ID: ${self:custom.awsconfig.aws_account_payer_id}
      octopus_resource: "totvs-cloudformation-templates"
      lambda_create_cloudtrail: "${self:service}-create_cloudtrail-${self:provider.stage}"
    runtime: python3.6
    memorySize: 256
    timeout: 300 # 300 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-create_account-${self:provider.stage}
    package:
      include:
        - src/lambda_create_account.py
        - src/model/*.py
    layers:
      - "arn:aws:lambda:us-east-2:826839167791:layer:model_octopus:13"
    events:
      - sqs:
         arn: 
          "arn:aws:sqs:${self:provider.region}:${self:custom.awsconfig.aws_account_id}:CreateAccount"
          #Fn::GetAtt: [ SQSCreateAccount , Arn ]
          
  request_creation_account:
    handler: src/lambda_controller_creation_account.lambda_handler
    runtime: python3.6
    memorySize: 256
    timeout: 30 # 30 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-controller_creation_account-${self:provider.stage}
    package:
      include:
        - src/lambda_controller_creation_account.py
    events:
      - http:
          path: /account/create
          method: post
          cors: true
          private: true
  
  request_account_id_created:
    handler: src/lambda_get_account_id_created.lambda_handler
    runtime: python3.6
    memorySize: 256
    timeout: 30 # 30 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-get_account_id_created-${self:provider.stage}
    package:
      include:
        - src/lambda_get_account_id_created.py
    events:
      - http:
          path: /account/id/{name_account}
          method: get
          cors: true
          private: true

  request_login_checktoken:
    handler: src/lambda_login_check_token.lambda_handler
    runtime: python3.6
    memorySize: 256
    timeout: 30 # 30 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-login_check_token-${self:provider.stage}
    package:
      include:
        - src/lambda_login_check_token.py
    events:
      - http:
          path: /account/checkToken
          method: post
          cors: true
          private: true

  request_get_account_organizations:
    handler: src/lambda_get_accounts_organizations.lambda_handler
    environment:
      PAYER_ID: ${self:custom.awsconfig.aws_account_payer_id}
    runtime: python3.6
    memorySize: 256
    timeout: 30 # 30 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-get_accounts_organizations-${self:provider.stage}
    package:
      include:
        - src/model/*.py
        - src/lambda_get_accounts_organizations.py
    layers:
      - "arn:aws:lambda:us-east-2:826839167791:layer:model_octopus:13"        
    events:
      - http:
          path: /account/organizations
          method: get
          cors: true
          private: true

  # send the data to sqs
  controller_compliance_new_check: 
    handler: src/lambda_controller_compliances.lambda_handler
    environment:
      URL_SQS_IAM: "https://sqs.${self:provider.region}.amazonaws.com/${self:custom.awsconfig.aws_account_id}/${self:custom.sqs_compliance_new_check}"
      URL_SQS_CIS: "https://sqs.${self:provider.region}.amazonaws.com/${self:custom.awsconfig.aws_account_id}/${self:custom.sqs_compliance_cis_new_check}"
      PAYER_ID: ${self:custom.awsconfig.aws_account_payer_id}
      LAMBDA_ORGANIZATION: ${self:service}-get_accounts_organizations-${self:provider.stage}
      # octopus_resource: "totvs-cloudformation-templates"
    runtime: python3.6
    memorySize: 256
    timeout: 30 # 30 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-controller_compliances-${self:provider.stage}
    package:
      include:
        - src/lambda_controller_compliances.py
        - src/model/*.py
    layers:
      - "arn:aws:lambda:us-east-2:826839167791:layer:model_octopus:13"
      - "arn:aws:lambda:us-east-2:826839167791:layer:requests:1"
    events:
      - http:
          path: /policy/compliance/iam/new
          method: post
          cors: true
          private: true
      - http:
          path: /policy/compliance/cis/new
          method: post
          cors: true
          private: true
  
  # receive the sqs data and also the requests from api gateway
  compliance_iam_account:
    handler: src/lambda_compliance_iam.lambda_handler
    environment:
      octopus_resource: totvs-cloudformation-templates 
    runtime: python3.6
    memorySize: 256
    timeout: 30 # 30 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-compliance_iam-${self:provider.stage}
    package:
      include:
        - src/model/*.py
        - src/lambda_compliance_iam.py
    layers:
      - "arn:aws:lambda:us-east-2:826839167791:layer:model_octopus:13"        
    events:
      - http:
          path: /policy/compliance/iam/check
          method: get
          cors: true
          private: true
      - http:
          path: /policy/compliance/iam/dates-available
          method: get
          cors: true
          private: true       
      - sqs:
         arn: 
          "arn:aws:sqs:${self:provider.region}:${self:custom.awsconfig.aws_account_id}:${self:custom.sqs_compliance_new_check}"

  # receive the requests from api gateway
  request_cis_compliance:
    handler: src/lambda_cis_compliance.lambda_handler
    runtime: python3.6
    memorySize: 256
    timeout: 30 # 30 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-lambda_cis_compliance-${self:provider.stage}
    package:
      include:
        - src/model/*.py
        - src/lambda_cis_compliance.py
    layers:
      - "arn:aws:lambda:us-east-2:826839167791:layer:model_octopus:13"        
    events:
      - http:
          path: /policy/compliance/cis/check
          method: get
          cors: true
          private: true
      - http:
          path: /policy/compliance/cis/dates-available
          method: get
          cors: true
          private: true
  
  # receive the sqs data
  proccess_data_cis_compliance:
    handler: src/lambda_aws_cis_foundation_benchmark_checklist.lambda_handler
    runtime: python3.6
    memorySize: 256
    timeout: 600 # 10 minutes
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-aws_cis_foundation_benchmark_checklist-${self:provider.stage}
    package:
      include:
        - src/model/*.py
        - src/lambda_aws_cis_foundation_benchmark_checklist.py
    layers:
      - "arn:aws:lambda:us-east-2:826839167791:layer:model_octopus:13"        
    events:      
      - sqs:
         arn: 
          "arn:aws:sqs:${self:provider.region}:${self:custom.awsconfig.aws_account_id}:${self:custom.sqs_compliance_cis_new_check}"
        batchSize: 2


  requests_manage_policy: 
    handler: src/lambda_manage_policy.lambda_handler
    runtime: python3.6
    memorySize: 256
    timeout: 30 # 30 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-manage_policy-${self:provider.stage}
    package:
      include:
        - src/lambda_manage_policy.py
        - src/model/*.py
    layers:
      - "arn:aws:lambda:us-east-2:826839167791:layer:model_octopus:13"
      #- "arn:aws:lambda:us-east-2:826839167791:layer:requests:1"
    events:
      - http:
          path: /policy/content
          method: get
          cors: true
      - http:
          path: /policy/available/trust
          method: get
          cors: true
          private: true
      - http:
          path: /policy/available/iam
          method: get
          cors: true
          private: true
      - http:
          path: /policy/available/role
          method: get
          cors: true
          private: true
      - http:
          path: /policy/update
          method: post
          cors: true
          private: true
      # - http:
      #     path: /policy/{policy_name}
      #     method: get
      #     cors: true
      # - http:
      #     path: /policy/update
      #     method: put
      #     cors: true
      # - http:
      #     path: /policy/delete
      #     method: delete
      #     cors: true

  # request_get_default_role_policy:
  #   handler: src/lambda_get_default_role_policy.lambda_handler
  #   environment:
  #     octopus_resource: "totvs-cloudformation-templates"
  #   runtime: python3.6
  #   memorySize: 256
  #   timeout: 30 # 30 seconds
  #   role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
  #   name: ${self:service}-get_default_role_policy-${self:provider.stage}
  #   package:
  #     include:
  #       - src/lambda_get_default_role_policy.py
  #   events:
  #     - http:
  #         path: /policy/default
  #         method: get
  #         cors: true

  request_manage_roles:
    handler: src/lambda_manage_role.lambda_handler
    environment:
      octopus_resource: "totvs-cloudformation-templates"
    runtime: python3.6
    memorySize: 256
    timeout: 30 # 30 seconds
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-manage_role-${self:provider.stage}
    package:
      include:
        - src/lambda_manage_role.py
    events:
      - http:
          path: /role/available
          method: get
          cors: true
          private: true
      - http:
          path: /role/{role_type}
          method: get
          cors: true
          private: true #https://serverless.com/framework/docs/providers/aws/events/apigateway#setting-api-keys-for-your-rest-api
      - http:
          path: /role/new
          method: post
          cors: true 
          private: true
      # - http:
      #     path: /role/update
      #     method: put
      #     cors: true
      - http:
          path: /role/delete
          method: delete
          cors: true
          private: true


  create_cloudtrail:
    handler: src/lambda_create_cloudtrail.lambda_handler
    environment:
      id_cloudtrail: 461835337376
      bucket_cloudtrail: totvs-cloudtrail
      name_cloudtrail: totvs-cloudtrail
    runtime: python3.6
    memorySize: 256
    timeout: 600 # 10 minutes
    role: arn:aws:iam::${self:custom.awsconfig.aws_account_id}:role/${self:custom.awsconfig.aws_role_lambda}
    name: ${self:service}-create_cloudtrail-${self:provider.stage}
    package:
      include:
        - src/model/*.py
        - src/lambda_create_cloudtrail.py
    layers:
      - "arn:aws:lambda:us-east-2:826839167791:layer:model_octopus:13"        
    events:      
      - sqs:
         arn: 
          "arn:aws:sqs:${self:provider.region}:${self:custom.awsconfig.aws_account_id}:${self:custom.sqs_compliance_cis_new_check}"
        batchSize: 2

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:provider.stage}
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    